version: '2'
volumes:
  rsync_data:
services:
  rsync:
    build: ./rsync
    privileged: true
    volumes:
      - 'rsync_data:/mnt/rsync_data'
  samba:
    image: dastrasmue/rpi-samba 
    command: -s "Public (readonly):/mount:ro:"
    volumes:
       - 'rsync_data:/mount'
    ports:
      - "139:139"
      - "445:445"
  